### ISSUE TITLE
Is it possible for Modpack makers to make a manual for the pack using MarkdownManual?

### ISSUE THREAD

**Issue by ChromaPIE** [MightyPirates/MarkdownManual#4]
Title.

**Comment by samuelh2005** [comment]
It is possible, but you need to make a "main" mod for the pack. Currently it is the only way  to do it.

**Comment by fnuecke** [comment]
The above.  While creation of a minimal mod to add a custom manual mostly just needs the steps described in the readme, I understand that this is not practical for everyone.  However, I currently don't plan to look into purely data-driven manual creation, and don't want to get anyone's hope up there, sorry.
