### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Cataratas** [MightyPirates/MarkdownManual#6]
Game crashes upon launch after updating fabric loader from 1.14.22 to 1.14.24.

[crash-2023-10-26_14.02.16-client.txt](https://github.com/MightyPirates/MarkdownManual/files/13180814/crash-2023-10-26_14.02.16-client.txt)

**Comment by Abalieno** [comment]
...what about 19.2?

**Comment by Abalieno** [comment]
Poking again, since tis3d depends on markdown manual, that crashes on recent fabric apis (1.19.2)
